disabled_rules: # Find all the available rules by running: `swiftlint rules`
  - file_length
  - line_length
  - force_try
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)